### ISSUE TITLE
i want to convert html table to markdown

### ISSUE THREAD

**Issue by adunStudio** [neocotic/html.md#69] opened 2016-11-02 08:12 UTC
but  html.md don't apply

**Comment by neocotic** [comment] 2016-11-07 14:11
@adunStudio This will be covered under #49 when we add support for GFM (GitHub Flavored Markdown).

> The work is currently on hold while I'm working on a whole new approach to this library, which I'm rewriting from scratch. The new library will be more open (MIT licensed) and much more modular so that presets like GFM can be added only when needed and avoids bloating the library while also allowing others to add their own plugins/presets for other tags or to replace builtin tag support.

I'm going to close this issue as a duplicate of #49.

**Closed by neocotic** 2016-11-07 14:11 UTC
